app/models.py
from . import db, login_manager
from datetime import datetime
from flask_login import UserMixin


class Permission:
    COMMENT = 0X02


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True)
    username = db.Column(db.String(20), unique=True)
    password_hash = db.Column(db.String(128))
    name = db.Column(db.String(64))
    about = db.Column(db.Text)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(60))
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    replied_id = db.Column(db.Integer, db.ForeignKey('comments.id'))
    replied = db.relationship('Comment', back_populates='replies',
                              remote_side=[id])
    replies = db.relationship('Comment', back_populates='replied',
                              cascade='all')

app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, Length
from flask_ckeditor import CKEditorField


class blog_form(FlaskForm):
    title = StringField('标题',validators=[Required(), Length(1, 60)])
    body = CKEditorField('内容', validators=[Required(), Length(10, 2000)])
    submit = SubmitField('提交')


class comment_form(FlaskForm):
    body = TextAreaField(render_kw={'placeholder': '写下您的评论'},
                         validators=[Required(), Length(1, 50)])
    submit = SubmitField('提交')

app/__init__.py
import os
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_ckeditor import CKEditor
from flask_login import LoginManager
import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
ckeditor = CKEditor()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'waring'
login_manager.login_message = '请先登陆才能观察这部分内容'


def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')
    app = Flask(__name__)
    app.config.from_object(config.config[config_name])

    # 扩展实例化
    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    ckeditor.init_app(app)

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')
    from .blog import blog as blog_blueprint
    app.register_blueprint(blog_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/admin/__init__.py
from flask import Blueprint
admin = Blueprint('admin', __name__)

app/blog/__init__.py
from flask import Blueprint
blog = Blueprint('blog', __name__)
from . import views

app/blog/views.py
import datetime

from flask import render_template, request, current_app, flash, \
    redirect, url_for
from flask_login import login_required,current_user
from . import blog
from .. import db
from ..models import Post, Comment, User
from .forms import blog_form, comment_form


@blog.route('/', defaults={'page': 1})
@blog.route('/page/<int:page>')
def home(page):
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()). \
        paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('index.html', pagination=pagination, posts=posts,
                           title='博客首页')


@blog.route('/show_post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get(post_id)
    comments = Comment.query.filter_by(post_id=post_id) \
        .order_by(Comment.timestamp.desc()).all()
    users = []
    for i in comments:
        users.append(User.query.get(i.author_id).username)
    form = comment_form()
    return render_template('detail.html',
                           post=post, result=zip(comments, users),
                           title='文章详情', form=form)


@blog.route('/myblog/<username>/', defaults={'page': 1})
@blog.route('/myblog/<username>/<int:page>')
@login_required
def my_blog(username, page):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('please login first')
        return redirect(url_for('auth.login'))
    user_id = user.id
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.filter_by(author_id=user_id) \
        .order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('index.html', pagination=pagination, posts=posts,
                           title='我的博客')


@blog.route('/about/<username>/')
@login_required
def about(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('please login first')
        return redirect(url_for('auth.login'))
    if user.about is None:
        user.about = '暂无介绍'
        if user.name is None:
            user.name = '暂无信息'
    return render_template('about.html', user=user, title='关于我')


@blog.route('/write/<username>', methods=['GET', 'POST'])
@login_required
def write_blog(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('please login first')
        return redirect(url_for('auth.login'))
    else:
        form = blog_form()
        user_id = user.id
        if form.validate_on_submit():
            timestamp = datetime.datetime.utcnow()
            post = Post(title=form.title.data, body=form.body.data,
                        author_id=user_id, timestamp=timestamp)
            db.session.add(post)
            db.session.commit()
            flash('submit post success')
            return redirect(url_for('blog.write_blog', username=username))
        return render_template('write.html', form=form)


@blog.route('/comment/<username>/<int:post_id>', methods=['POST'])
@login_required
def write_comment(username, post_id):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('please login first')
        return redirect(url_for('auth.login'))
    else:
        form = comment_form()
        user_id = user.id
        if form.validate_on_submit():
            comment = Comment(author_id=user_id, post_id=post_id,
                              body=form.body.data)
            db.session.add(comment)
            db.session.commit()
            flash('submit comment success')
            return redirect(url_for('blog.show_post', post_id=post_id))
        else:
            flash('warning message')
        return redirect(url_for('blog.show_post', post_id=post_id))

app/templates/about.html
{% extends 'base.html' %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            {% if user %}
                <h1>{{ user.username }}</h1>
                <h2>{{ user.email }}</h2>
                <h3>{{ user.about }}</h3>
                <h3>{{ user.name }}</h3>
                <h3>
                    <a href="{{ url_for('blog.my_blog',username=user.username) }}">
                        他的博客
                    </a>
                </h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{{ title }}{% endblock %}</title>
		<link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}" />
		<script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.min.js')}}"></script>
	    {{ moment.include_moment(local_js=url_for('static',filename='js/moment-with-locales.js')) }}

    </head>
	<body>
    <div class="container-fluid">
        <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('blog.home') }}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('blog.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('blog.my_blog',username=current_user.username) }}">my blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('blog.about',username=current_user.username) }}">about me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('blog.write_blog',username=current_user.username) }}">write blog</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
        </div>
        </nav>
        </div>
    </div>
    {{ moment.locale(auto_detect=True) }}
	</body>
    {% block body %}
    {% endblock %}
{% block script %}
{% endblock %}
</html>

app/templates/detail.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block body %}
    <div class="container">
    <h3 class="text-primary">
        {{ post.title }}
    </h3>
    <h5 class="text-primary">
        {{ post.timestamp }}
    </h5>
    <p class="text-primary">
        {{ post.body|striptags }}
    </p>
    {% if current_user.is_authenticated %}
    <form class="form-group" method="post"
          action="{{ url_for('blog.write_comment',username=current_user.username,post_id=post.id) }}">
    {{ form.csrf_token }}
        <div class="mb-3">
        <label class="form-label">写下你的评论</label>
        {{ form.body(class="form-control") }}
        {{ form.submit(class="form-btn") }}
    </div>
    </form>
    {% else %}
    <div>
        <a class="btn" type="button" href="{{ url_for('auth.login') }}">
            评论请先登陆
        </a>
    </div>
    {% endif %}
        <h4>Comments</h4>
        <div class="list-group">
        {% for comment,user in result %}
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-primary"><a href="{{ url_for('blog.about',username=user) }}">{{ user }}</a>
                <small class="text-muted">#{{ loop.revindex }}</small>
                </h5>
                <small>
                    {{ comment.timestamp }}
                </small>
            </div>
            <p class="mb-1">{{ comment.body|striptags }}</p>
        {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/edit_note.html
{% from 'macros.html' import form_field %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {{ form.csrf_token }}
        {{ form_field(form.body,row=5,cols=50) }}
        {{ form.submit }}
    </form>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block body %}
    <div class="container">
    {% if posts %}
        {% for post in posts %}
            <h3 class="text-primary">
                <a href="{{ url_for('blog.show_post',post_id=post.id) }}"></a>
            {{ post.title }}
                <small>{{ moment(post.timestamp).fromNow(refresh=True) }}</small>
            </h3>
            <p>
            {{ post.body|striptags|truncate }}
            <small>
                <a href="{{ url_for('blog.show_post',post_id=post.id) }}">
                    detail
                </a>
            </small>
            </p>
        {% endfor %}
    {% endif %}
    <div class="page-footer">
        {{ render_pagination(pagination) }}
    </div>

    </div>
{% endblock %}

app/templates/login.html
{% from 'bootstrap/form.html' import render_form %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        {{ render_form(form,action=request.full_path) }}
        {% if operation=='登陆' %}
        <a class="btn" type="button" href="{{ url_for('auth.login') }}">
            {{ operation }}</a>
        {% else %}
        <a class="btn" type="button" href="{{ url_for('auth.register') }}">
            {{ operation }}</a>
        {% endif %}
    </div>
    {% for msg in get_flashed_messages() %}
        <p class="err">{{ msg }}</p>
    {% endfor %}
</body>
</html>

app/templates/macros.html
{% macro form_field(field) %}
    {{ field.label }}<br>
    {{ field(**kwargs) }}<br>
    {% if field.errors %}
    {% for error in field.erroes %}
    <small class="inner">{{ error }}</small>
    {% endfor %}
    {% endif %}
{% endmacro %}

app/templates/write.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block body %}
    <div class="form-group">
        {{ render_form(form,action=request.full_path) }}
    </div>
    {% for msg in get_flashed_messages() %}
        <p class="err">{{ msg }}</p>
    {% endfor %}
{% endblock %}
{% block script %}
{{ super() }}
{{ ckeditor.load() }}
{% endblock %}